#ifndef ARROW_TYPE_H
#define ARROW_TYPE_H

typedef enum {
    AR_EMPTY,
    AR_ARROW,
    AR_SOURCE,
    AR_BLOCKER,
    AR_DELAY,
    AR_DETECTOR,
    AR_SPLITTER_UP_DOWN,
    AR_SPLITTER_UP_RIGHT,
    AR_SPLITTER_UP_RIGHT_LEFT,
    AR_IMPULSE,
    AR_BLUE_ARROW,
    AR_DIAGONAL_ARROW,
    AR_BLUE_SPLITTER_UP_UP,
    AR_BLUE_SPLITTER_RIGHT_UP,
    AR_BLUE_SPLITTER_UP_DIAGONAL,
    AR_LOGIC_NOT,
    AR_LOGIC_AND,
    AR_LOGIC_XOR,
    AR_LATCH,
    AR_FLIP_FLOP,
    AR_RANDOM,
    AR_BUTTON,
    AR_LEVEL_SOURCE,
    AR_LEVEL_TARGET,
    AR_DIRECTIONAL_BUTTON,
} ArrowType;

#endif
