#ifndef EVENTS_H
#define EVENTS_H

#include <raylib.h>

enum InputEvent {
    ARROW_NORTH = KEY_W,
    ARROW_SOUTH = KEY_S,
    ARROW_WEST = KEY_A,
    ARROW_EAST = KEY_D,
    ARROW_FLIP = KEY_F,
    ARROW_REMOVE = KEY_R,
    ARROW_MENU = KEY_TAB,
    SELECT = KEY_E,
    SELECTED_REMOVE = KEY_BACKSPACE,
    SELECTED_COPY = KEY_C,
    CLIPBOARD_PASTE = KEY_V,
    HOTBAR1 = KEY_ONE,
    HOTBAR2 = KEY_TWO,
    HOTBAR3 = KEY_THREE,
    HOTBAR4 = KEY_FOUR,
    HOTBAR5 = KEY_FIVE,
    HOTBAR_DESELECT = KEY_GRAVE,
    HOTBAR_PREVIOUS = KEY_Z,
    HOTBAR_NEXT = KEY_X,
    PIPETTE = KEY_Q,
    MOVE_FORWARD = KEY_UP,
    MOVE_BACK = KEY_DOWN,
    MOVE_LEFT = KEY_LEFT,
    MOVE_RIGHT = KEY_RIGHT,
    CENTER = KEY_H,
    ZOOM_IN = KEY_EQUAL,
    ZOOM_OUT = KEY_MINUS,
    ZOOM_RESET = KEY_EQUAL,
    SIGNALS_REMOVE = KEY_N,
    PAUSE = KEY_SPACE,
    MAP_MENU = KEY_ESCAPE,
    TICK_STEP = KEY_ENTER,
    ARROW_SET = MOUSE_BUTTON_LEFT,
    ARROW_INTERACT = MOUSE_BUTTON_RIGHT,
    CAMERA_MOVE = MOUSE_BUTTON_MIDDLE,
};

#endif
